'use client';

import { useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';

type Action = 'APPROVE' | 'REJECT' | 'START_RESEARCH' | 'START_SCRIPTING' | 'START_CREATIVE' | 'START_PRODUCTION' | 'START_QA' | 'COMPLETE_PRODUCTION';

type DashboardData = { source:string; generatedAt?:string; channel?:any; counts?:any; opportunities?:any[]; pipeline?:any[]; scheduled?:any[]; learnings?:any[]; decisions?:any[]; recentHistory?:any[]; metrics?:any[]; flags?:string[]; message?:string };

const snapshot: DashboardData = { source:'SNAPSHOT', channel:{name:'How The World Works',niche:'Engineering / Technology / Infrastructure',promise:'The systems, machines and ideas behind everyday life.'}, counts:{opportunities:4,researching:4,approved:0,in_production:0,scheduled:5,published:0,performance:0,learnings:0,decisions:0}, opportunities:[{id:'',title:'How a MASSIVE Steel Block Becomes a Giant Industrial Gear',pillar:'Machines',priority:'HIGH',status:'REVIEW',next_action:'Research technical process and packaging'},{id:'',title:'Why Modern Factories Look Almost Empty',pillar:'Systems',priority:'MEDIUM',status:'REVIEW',next_action:'Research automation economics and visuals'},{id:'',title:'The Machines That Turn Pressure Into Power',pillar:'Technology',priority:'MEDIUM',status:'REVIEW',next_action:'Research hydraulic systems and examples'},{id:'',title:'How Robots Are Replacing the Most Repetitive Factory Jobs',pillar:'Technology',priority:'MEDIUM',status:'REVIEW',next_action:'Research factory robotics evidence'}], pipeline:[{title:'The Giant Machine That Eats the Earth',current_state:'READY_TO_PUBLISH',production_status:'COMPLETE',publication_status:'SCHEDULED'},{title:'How Does a Giant Tunnel Boring Machine Actually Move Underground?',current_state:'READY_TO_PUBLISH',production_status:'COMPLETE',publication_status:'SCHEDULED'}], scheduled:[{title:'The Giant Machine That Eats the Earth',platform:'YouTube',scheduled_at:'2026-09-17 16:00',status:'PENDING'},{title:'The Giant Machine That Eats the Earth',platform:'TikTok',scheduled_at:'2026-09-17 10:00',status:'PENDING'},{title:'How Does a Giant Tunnel Boring Machine Actually Move Underground?',platform:'YouTube',scheduled_at:'2026-09-18 16:00',status:'PENDING'}], learnings:[], flags:['4 content items are researching.','5 publication records are pending; none is published.','NO DATA YET: first-party performance metrics are not available.'], decisions:[], recentHistory:[], metrics:[] };

function fmtDate(value?: string) { if (!value) return '—'; return new Date(value).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}); }
function tone(value?: string) { const v=String(value||'').toUpperCase(); if(['HIGH','PUBLISHED','COMPLETE','READY_TO_PUBLISH','APPROVED'].includes(v)) return 'positive'; if(['MEDIUM','REVIEW','PENDING','RESEARCHING','IN_PROGRESS','SCRIPTING','CREATIVE','PRODUCTION','QA'].includes(v)) return 'warn'; if(['FAILED','CANCELLED','IGNORE','REJECTED'].includes(v)) return 'danger'; return ''; }

export default function Home(){
  const [data,setData]=useState<DashboardData>(snapshot); const [loading,setLoading]=useState(true); const [active,setActive]=useState('overview'); const [actingId,setActingId]=useState<string|null>(null); const [actionMessage,setActionMessage]=useState('');
  async function refresh(){setLoading(true); try{const r=await fetch('/api/dashboard',{cache:'no-store'}); const j=await r.json(); setData(j.source==='NEON'?j:snapshot);}catch{setData(snapshot);}finally{setLoading(false);}}
  async function performAction(action: Action, opportunityId?: string, contentItemId?: string, title='item'){
    if(!opportunityId&&!contentItemId){setActionMessage('SNAPSHOT mode: live actions require NEON LIVE.');return;}
    let reason='';
    if(action==='REJECT') reason=window.prompt(`Reason for rejecting:\n${title}`,'')||'';
    if(action!=='REJECT'&&!window.confirm(`${action.replaceAll('_',' ')}?\n\n${title}`)) return;
    const key=opportunityId||contentItemId||null; setActingId(key); setActionMessage('');
    try{const r=await fetch('/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,opportunityId,contentItemId,reason})}); const result=await r.json(); if(!r.ok||!result.ok) throw new Error(result.message||'Action failed'); setActionMessage(`${action.replaceAll('_',' ')} recorded for “${title}”.`); await refresh();}catch(error:unknown){setActionMessage(error instanceof Error?error.message:String(error));}finally{setActingId(null);}
  }
  useEffect(()=>{refresh();},[]);
  const c=data.counts||snapshot.counts; const nav=['overview','radar','pipeline','schedule','learning'];
  const visibleOpps=useMemo(()=> (data.opportunities||[]).filter(o=>!['REJECTED','ARCHIVED'].includes(String(o.status||'').toUpperCase())).slice(0,8),[data.opportunities]);
  const visiblePipeline=useMemo(()=> (data.pipeline||[]).slice(0,12),[data.pipeline]); const visibleSchedule=useMemo(()=> (data.scheduled||[]).slice(0,12),[data.scheduled]); const visibleLearnings=useMemo(()=> (data.learnings||[]).slice(0,8),[data.learnings]); const visibleHistory=useMemo(()=> (data.recentHistory||[]).slice(0,10),[data.recentHistory]);
  const stats=[['OPPORTUNITIES',c.opportunities,'Radar'],['RESEARCHING',c.researching,'Active'],['APPROVED',c.approved,'Gate'],['IN PRODUCTION',c.in_production,'Creative'],['SCHEDULED',c.scheduled,'Pending'],['PUBLISHED',c.published,'Live']];
  return <main>
    <header className="topbar"><div><div className="eyebrow">MEDIA OPERATING SYSTEM / COMMAND CENTER</div><h1>{data.channel?.name||'How The World Works'}</h1><p>{data.channel?.promise||snapshot.channel?.promise}</p></div><div className="actions"><span className="status-dot"/><span className="badge">{data.source==='NEON'?'NEON LIVE':'SNAPSHOT'}</span><button onClick={refresh}>{loading?'Refreshing…':'Refresh'}</button></div></header>
    <nav className="nav-tabs" aria-label="Dashboard sections">{nav.map(item=><button key={item} className={active===item?'nav-tab active':'nav-tab'} onClick={()=>setActive(item)}>{item}</button>)}</nav>
    {actionMessage&&<div className="action-message">{actionMessage}</div>}
    {active==='overview'&&<>
      <section className="hero-grid"><div className="hero-card"><div className="hero-label">CHANNEL BRAIN</div><div className="hero-title">{data.channel?.niche||snapshot.channel?.niche}</div><div className="hero-copy">Discovery → research → production → publication → learning, with Neon as the system of record.</div></div><div className="hero-card decision"><div className="hero-label">DECISION QUEUE</div><div className="hero-title">{c.opportunities||0} opportunities need review</div><div className="hero-copy">Radar can research and prepare. Human approval remains the editorial gate.</div></div></section>
      <section className="stats">{stats.map(([a,b,d])=><div className="stat" key={a as string}><div className="stat-kicker">{a}</div><div className="stat-value">{b}</div><div className="stat-note">{d}</div></div>)}</section>
      <section className="grid-2"><Panel title="Opportunity Radar" meta="Latest">{visibleOpps.map((o,i)=><Opportunity key={o.id||i} item={o} onAction={performAction} actingId={actingId}/>)}</Panel><Panel title="Production Pipeline" meta={`${visiblePipeline.length} items`}>{visiblePipeline.map((p,i)=><PipelineRow key={p.id||i} item={p} onAction={performAction} actingId={actingId}/>)}</Panel></section>
      <section className="grid-2"><Panel title="Publication Schedule" meta="Metricool">{visibleSchedule.slice(0,6).map((p,i)=><ScheduleRow key={i} item={p}/>)}</Panel><Panel title="Signals & Flags" meta="Learning Engine">{(data.flags||[]).map((f,i)=><div className="flag" key={i}><span>●</span>{f}</div>)}<div className="mini-grid"><div><strong>{c.performance||0}</strong><span>metric samples</span></div><div><strong>{c.learnings||0}</strong><span>durable learnings</span></div><div><strong>{c.decisions||0}</strong><span>decisions logged</span></div></div></Panel></section>
    </>}
    {active==='radar'&&<section className="single-panel"><Panel title="Opportunity Radar" meta={`${visibleOpps.length} shown`}>{visibleOpps.map((o,i)=><Opportunity key={o.id||i} item={o} detailed onAction={performAction} actingId={actingId}/>)}</Panel></section>}
    {active==='pipeline'&&<section className="single-panel"><Panel title="Production Pipeline" meta={`${visiblePipeline.length} items`}>{visiblePipeline.map((p,i)=><PipelineRow key={p.id||i} item={p} detailed onAction={performAction} actingId={actingId}/>)}</Panel></section>}
    {active==='schedule'&&<section className="single-panel"><Panel title="Publication Schedule" meta="Metricool records">{visibleSchedule.map((p,i)=><ScheduleRow key={i} item={p} detailed/>)}</Panel></section>}
    {active==='learning'&&<section className="grid-2"><Panel title="Latest Learnings" meta={`${visibleLearnings.length} shown`}>{visibleLearnings.length?visibleLearnings.map((l,i)=><div className="learning-card" key={i}><div className="learning-title">{l.learning||'Learning recorded'}</div><div className="learning-copy">{l.action||l.interpretation||'No action recorded.'}</div><div className="learning-meta"><span className="badge">{l.confidence||'UNSPECIFIED'}</span><span>{fmtDate(l.created_at)}</span></div></div>):<div className="empty">No durable learnings yet. The system will say NO DATA YET rather than fabricate a lesson.</div>}</Panel><Panel title="Historical State Changes" meta={`${visibleHistory.length} shown`}>{visibleHistory.length?visibleHistory.map((h,i)=><div className="history" key={i}><strong>{h.title}</strong><div className="sub">{h.field_name}: {h.old_value||'—'} → {h.new_value||'—'} · {h.source||'unknown'} · {fmtDate(h.changed_at)}</div></div>):<div className="empty">No state history available yet.</div>}</Panel></section>}
    <footer>Source: {data.source} · {data.generatedAt?new Date(data.generatedAt).toLocaleString('en-US'):'fallback snapshot'} · Neon is the system of record</footer>
  </main>;
}

function Panel({title,meta,children}:{title:string;meta:string;children:ReactNode}){return <div className="panel"><div className="panel-head"><h2>{title}</h2><span>{meta}</span></div>{children}</div>;}

function Opportunity({item,detailed=false,onAction,actingId}:{item:any;detailed?:boolean;onAction:(action:Action,opportunityId?:string,contentItemId?:string,title?:string)=>void;actingId:string|null}){
  const actionable=['REVIEW','RESEARCHING','APPROVED'].includes(String(item.status||'').toUpperCase()); const busy=!!item.id&&actingId===item.id;
  return <div className="op"><div className="op-top"><div className="op-title">{item.title}</div><div className="chips"><span className="badge">{item.pillar}</span><span className={`badge ${tone(item.priority)}`}>{item.priority}</span><span className={`badge ${tone(item.status)}`}>{item.status}</span></div></div>{detailed&&item.metadata&&<div className="op-next">Signals recorded in Radar metadata.</div>}<div className="op-next">Next: {item.next_action||'Review editorial opportunity'}</div><div className="sub">Discovered {fmtDate(item.discovered_at)}</div>{actionable&&item.id&&<div className="op-actions"><button disabled={busy} onClick={()=>onAction('START_RESEARCH',item.id,undefined,item.title)}>Research</button><button disabled={busy} onClick={()=>onAction('APPROVE',item.id,undefined,item.title)}>Approve</button><button className="danger-btn" disabled={busy} onClick={()=>onAction('REJECT',item.id,undefined,item.title)}>Reject</button></div>}</div>;
}

function PipelineRow({item,detailed=false,onAction,actingId}:{item:any;detailed?:boolean;onAction:(action:Action,opportunityId?:string,contentItemId?:string,title?:string)=>void;actingId:string|null}){
  const state=String(item.current_state||item.status||'').toUpperCase(); const busy=!!item.id&&actingId===item.id;
  const next: {action: Action; label:string}|null= state==='APPROVED'?{action:'START_SCRIPTING',label:'Start scripting'}:state==='SCRIPTING'?{action:'START_CREATIVE',label:'Start creative'}:state==='CREATIVE'?{action:'START_PRODUCTION',label:'Start production'}:state==='PRODUCTION'?{action:'START_QA',label:'Run QA'}:state==='QA'?{action:'COMPLETE_PRODUCTION',label:'Mark ready'}:null;
  return <div className={detailed?'pipeline-card detailed-pipeline':'pipeline-card'}><div className="pipeline-title">{item.title}</div><div className="pipeline-meta"><span className={`state ${tone(item.content_status||state)}`}>{item.content_status||state||'UNKNOWN'}</span><span>production {item.production_status||'—'}</span><span>publication {item.publication_status||'—'}</span><span>updated {fmtDate(item.updated_at)}</span></div>{next&&item.id&&<div className="pipeline-actions"><button disabled={busy} onClick={()=>onAction(next.action,undefined,item.id,item.title)}>{next.label}</button></div>}</div>;
}

function ScheduleRow({item,detailed=false}:{item:any;detailed?:boolean}){return <div className="row"><div className="row-main"><strong>{item.title}</strong><div className="sub">{item.platform} · {fmtDate(item.scheduled_at)}{item.published_at?` · published ${fmtDate(item.published_at)}`:''}</div>{detailed&&item.external_post_id&&<div className="sub">External post: {item.external_post_id}</div>}</div><span className={`badge ${tone(item.status)}`}>{item.status}</span></div>;}
