'use client';

import { useEffect, useState } from 'react';

type DashboardData = { source:string; generatedAt?:string; channel?:any; counts?:any; opportunities?:any[]; pipeline?:any[]; scheduled?:any[]; learnings?:any[]; flags?:string[]; message?:string };
const snapshot: DashboardData = {source:'SNAPSHOT',channel:{name:'How The World Works',niche:'Engineering / Technology / Infrastructure',promise:'The systems, machines and ideas behind everyday life.'},counts:{opportunities:4,researching:4,approved:0,in_production:0,scheduled:5,published:0,performance:0,learnings:0,decisions:0},opportunities:[{title:'How a MASSIVE Steel Block Becomes a Giant Industrial Gear',pillar:'Machines',priority:'HIGH',status:'REVIEW',next_action:'Research technical process and packaging'},{title:'Why Modern Factories Look Almost Empty',pillar:'Systems',priority:'MEDIUM',status:'REVIEW',next_action:'Research automation economics and visuals'},{title:'The Machines That Turn Pressure Into Power',pillar:'Technology',priority:'MEDIUM',status:'REVIEW',next_action:'Research hydraulic systems and examples'},{title:'How Robots Are Replacing the Most Repetitive Factory Jobs',pillar:'Technology',priority:'MEDIUM',status:'REVIEW',next_action:'Research factory robotics evidence'}],pipeline:[{title:'The Giant Machine That Eats the Earth',current_state:'READY_TO_PUBLISH'},{title:'How Does a Giant Tunnel Boring Machine Actually Move Underground?',current_state:'READY_TO_PUBLISH'}],scheduled:[{title:'The Giant Machine That Eats the Earth',platform:'YouTube',scheduled_at:'2026-09-17 16:00',status:'PENDING'},{title:'The Giant Machine That Eats the Earth',platform:'TikTok',scheduled_at:'2026-09-17 10:00',status:'PENDING'},{title:'How Does a Giant Tunnel Boring Machine Actually Move Underground?',platform:'YouTube',scheduled_at:'2026-09-18 16:00',status:'PENDING'}],learnings:[],flags:['4 content items are researching.','5 publication records are pending; none is published.','No durable learnings yet.']};

export default function Home(){
 const [data,setData]=useState<DashboardData>(snapshot); const [loading,setLoading]=useState(true);
 async function refresh(){setLoading(true); try{const r=await fetch('/api/dashboard',{cache:'no-store'}); const j=await r.json(); setData(j.source==='NEON'?j:snapshot)}catch{setData(snapshot)} finally{setLoading(false)}}
 useEffect(()=>{refresh()},[]); const c=data.counts||snapshot.counts;
 const stats=[['OPPORTUNITIES',c.opportunities,'Radar'],['RESEARCHING',c.researching,'Active'],['APPROVED',c.approved,'Gate'],['IN PRODUCTION',c.in_production,'Creative'],['SCHEDULED',c.scheduled,'Pending'],['PUBLISHED',c.published,'Live']];
 return <main><header className="topbar"><div><div className="eyebrow">MEDIA OPERATING SYSTEM</div><h1>{data.channel?.name||'How The World Works'}</h1><p>{data.channel?.promise||snapshot.channel?.promise}</p></div><div className="actions"><span className="badge">{data.source==='NEON'?'NEON LIVE':'SNAPSHOT'}</span><button onClick={refresh}>{loading?'Refreshing…':'Refresh'}</button></div></header>
 <section className="hero-grid"><div className="hero-card"><div className="hero-label">CHANNEL BRAIN</div><div className="hero-title">{data.channel?.niche||snapshot.channel?.niche}</div><div className="hero-copy">Operational view of discovery, research, production, publication and learning.</div></div><div className="hero-card decision"><div className="hero-label">DECISION QUEUE</div><div className="hero-title">{c.opportunities||0} opportunities need review</div><div className="hero-copy">Radar is researching and preparing the next editorial decisions. Production does not start automatically.</div></div></section>
 <section className="stats">{stats.map(([a,b,d])=><div className="stat" key={a as string}><div className="stat-kicker">{a}</div><div className="stat-value">{b}</div><div className="stat-note">{d}</div></div>)}</section>
 <section className="grid-2"><div className="panel"><div className="panel-head"><h2>Opportunity Radar</h2><span>Latest</span></div>{(data.opportunities||[]).slice(0,6).map((o,i)=><div className="op" key={i}><div className="op-title">{o.title}</div><div className="chips"><span className="badge">{o.pillar}</span><span className="badge">{o.priority}</span><span className="badge">{o.status}</span></div><div className="op-next">Next: {o.next_action}</div></div>)}</div>
 <div className="panel"><div className="panel-head"><h2>Production Pipeline</h2><span>{(data.pipeline||[]).length} items</span></div>{(data.pipeline||[]).slice(0,8).map((p,i)=><div className="row" key={i}><div className="row-main"><strong>{p.title}</strong><div className="sub">{p.current_state}</div></div></div>)}</div></section>
 <section className="grid-2"><div className="panel"><div className="panel-head"><h2>Publication Schedule</h2><span>Metricool</span></div>{(data.scheduled||[]).slice(0,8).map((p,i)=><div className="row" key={i}><div className="row-main"><strong>{p.title}</strong><div className="sub">{p.platform} · {p.scheduled_at}</div></div><span className="badge">{p.status}</span></div>)}</div>
 <div className="panel"><div className="panel-head"><h2>Signals & Flags</h2><span>Learning Engine</span></div>{(data.flags||[]).map((f,i)=><div className="flag" key={i}><span>●</span>{f}</div>)}{!(data.flags||[]).length&&<div className="empty">No active flags.</div>}<div className="empty">Learnings stored: {c.learnings||0}</div></div></section>
 <footer>Source: {data.source} · {data.generatedAt?new Date(data.generatedAt).toLocaleString('en-US'): 'fallback snapshot'}</footer></main>
}
